//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManage.RestaurantServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantServices.RestaurantServicesSoap")]
    public interface RestaurantServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNhanVien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNhanVien", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RestaurantServicesSoapChannel : RestaurantManage.RestaurantServices.RestaurantServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServicesSoapClient : System.ServiceModel.ClientBase<RestaurantManage.RestaurantServices.RestaurantServicesSoap>, RestaurantManage.RestaurantServices.RestaurantServicesSoap {
        
        public RestaurantServicesSoapClient() {
        }
        
        public RestaurantServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllNhanVien() {
            return base.Channel.GetAllNhanVien();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllNhanVienAsync() {
            return base.Channel.GetAllNhanVienAsync();
        }
        
        public System.Data.DataTable Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
